import os
import time
import pandas as pd
import yfinance as yf

def download_stocks(tickers, start_date='2020-01-01', end_date='2025-01-01'):

    # Define project root and data directory
    project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
    data_dir = os.path.join(project_root, "data", "raw")
    os.makedirs(data_dir, exist_ok=True)

    # Download stock data
    all_data = pd.DataFrame()
    for ticker in tickers:
        data = yf.download(ticker, start=start_date, end=end_date, auto_adjust=True)
        # Keep only Close and Volume
        features = data[['Close', 'Volume']].copy()
        features.columns = [f"{ticker}_Close", f"{ticker}_Volume"]
        all_data = pd.concat([all_data, features], axis=1)
        time.sleep(1)  # Avoid hitting API limits

    # Compute daily returns
    returns = all_data[[col for col in all_data.columns if "_Close" in col]].pct_change().dropna()
    volume = all_data[[col for col in all_data.columns if "_Volume" in col]].iloc[1:]

    # Merge returns and volume
    ml_data = pd.concat([returns, volume], axis=1)
    ml_data = ml_data.sort_index().reset_index(drop=True)

    # Compute market average
    ml_data["Market_Avg"] = ml_data[[f"{t}_Close" for t in tickers]].mean(axis=1)

    # Generate features for each ticker
    for t in tickers:
        r = ml_data[f"{t}_Close"]
        v = ml_data[f"{t}_Volume"]

        # Lagged returns
        ml_data[f"{t}_Lag1"] = r.shift(1)
        ml_data[f"{t}_Lag5"] = r.shift(5)
        ml_data[f"{t}_Lag10"] = r.shift(10)

        # Rolling volatility
        ml_data[f"{t}_Volatility5"] = r.rolling(5).std()
        ml_data[f"{t}_Volatility20"] = r.rolling(20).std()

        # Rolling mean
        ml_data[f"{t}_Mean5"] = r.rolling(5).mean()
        ml_data[f"{t}_Mean20"] = r.rolling(20).mean()

        # Rolling correlation with market average
        ml_data[f"{t}_CrossCorr5"] = r.rolling(5).corr(ml_data["Market_Avg"])

        # Volume trends
        ml_data[f"{t}_Vol_Mean5"] = v.rolling(5).mean()
        ml_data[f"{t}_Vol_Change"] = v.pct_change()

    # Drop rows with NaN values generated by rolling calculations
    ml_data = ml_data.dropna().reset_index(drop=True)

    path = os.path.join(data_dir, "TRAINING_DATA.csv")
    ml_data.to_csv(path, index=False)