import pandas as pd
from .optimized_weights import optimizer
from .model_predictions import load_models
import os
from .save_next_day_data import download_next_day_data
from .config import get_data_path
from datetime import date

def next_day_weights(tickers, initial_value):

    # Download stock data only if todays stock data has not already been downloaded
    data_dir = get_data_path()
    files = list(data_dir.iterdir())
    current_date = date.today()
    have_current_day_data = False
    for file in files:
        if file.name == current_date:
            have_current_day_data = True
            break
    all_data = pd.DataFrame()
    if have_current_day_data:
        print("Need to download data")
        all_data = download_next_day_data(tickers)
    else:
        print("Already have data")
        path = os.path.join(data_dir,f"{current_date}.csv")
        all_data = pd.read_csv(path)


    

    # Compute daily returns
    returns = all_data[[col for col in all_data.columns if "_Returns" in col]].pct_change().dropna()
    volume = all_data[[col for col in all_data.columns if "_Volume" in col]].iloc[1:]
    print(all_data.head())
    # Merge returns and volume
    current_day_data = pd.concat([returns, volume], axis=1)
    current_day_data = current_day_data.sort_index().reset_index(drop=True)
    print(current_day_data.head())
    # Compute market average
    current_day_data["Market_Avg"] = current_day_data[[f"{t}_Returns" for t in tickers]].mean(axis=1)

    # Generate features for each ticker
    for t in tickers:
        r = current_day_data[f"{t}_Returns"]
        v = current_day_data[f"{t}_Volume"]

        # Lagged returns
        current_day_data[f"{t}_Lag1"] = r.shift(1)
        current_day_data[f"{t}_Lag5"] = r.shift(5)
        current_day_data[f"{t}_Lag10"] = r.shift(10)

        # Rolling volatility
        current_day_data[f"{t}_Volatility5"] = r.rolling(5).std()
        current_day_data[f"{t}_Volatility20"] = r.rolling(20).std()

        # Rolling mean
        current_day_data[f"{t}_Mean5"] = r.rolling(5).mean()
        current_day_data[f"{t}_Mean20"] = r.rolling(20).mean()

        # Rolling correlation with market average
        current_day_data[f"{t}_CrossCorr5"] = r.rolling(5).corr(current_day_data["Market_Avg"])

        # Volume trends
        current_day_data[f"{t}_Vol_Mean5"] = v.rolling(5).mean()
        current_day_data[f"{t}_Vol_Change"] = v.pct_change()

    # Drop rows with NaN values generated by rolling calculations
    current_day_data = current_day_data.dropna().reset_index(drop=True)

    print(current_day_data.head())

    models = load_models(tickers)
    path = os.path.join(data_dir,"TRAINING_DATA.csv")
    df = pd.read_csv(path)
    mu_vector = []

    returns = df[[f"{ticker}_Returns" for ticker in tickers]]

    returns = returns.dropna()
    cov_matrix = returns.cov().values  # n x n numpy array
    print(current_day_data.head())

    # Predict next-day return for each ticker
    for i, ticker in enumerate(tickers):
        # Features for prediction: all columns related to the ticker except returns
        features = [col for col in current_day_data.columns if ticker in col and "Returns" not in col]
        #df = df.shift(-horizon)
        # Use the last available row as today's features
        last_features = current_day_data[features].iloc[[-1]]  # double brackets keep it as DataFrame
        pred = models[i].predict(last_features)

        # Store the 1-day ahead prediction
        mu_vector.append(pred[0])

    

    weights = optimizer(mu_vector, cov_matrix)
    print(weights)
    return weights

    



